// Screenshot-Tour durch alle Bildschirme: node scripts/tour.mjs <outdir>
import { chromium } from 'playwright';
import { launchOpts } from './browser.mjs';
import path from 'node:path';
import { distUrl } from './serve.mjs';

const out = process.argv[2] ?? '.';
const only = process.argv[3];
const file = await distUrl();
const browser = await chromium.launch(launchOpts());
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_CERT')) errors.push(m.text()); });
await page.goto(file);
await page.waitForTimeout(700);
await page.click('text=Loslegen');
// Spielstand aufbauen
await page.evaluate(() => {
  const g = window.__game, A = g.actions, s = g.state;
  s.credits = 40_000_000;
  const a = s.stations[0];
  A.queueModule(s, a.id, 'prod_refinedmetals');
  A.queueModule(s, a.id, 'storage_liquid');
  A.queueModule(s, a.id, 'prod_graphene');
  A.buyShip(s, 'alligator_min', a.id);
  A.buyShip(s, 'alligator_gas', a.id);
  A.buyShip(s, 'boa', a.id);
  g.step(3 * 3600);
  while (g.claim().ok);
  const r = A.foundStation(s, 'zhin', 60, 55);
  for (const d of ['storage_container', 'dock_m', 'prod_energycells', 'prod_hullparts']) { s.blueprints.includes('prod_' + d) || true; A.queueModule(s, r.id, d); }
  A.buyBlueprint(s, 'prod_hullparts', 'v-zhin');
  A.queueModule(s, r.id, 'prod_hullparts');
  A.buyShip(s, 'boa', r.id);
  g.step(2 * 3600);
  while (g.claim().ok);
  g.refresh();
});
await page.waitForTimeout(800);
const shot = async (n) => { if (!only || n.startsWith(only)) await page.screenshot({ path: `${out}/tour-${n}.png` }); };
const act = async (sel) => { await page.click(sel); await page.waitForTimeout(350); };
await shot('01-map');
await page.evaluate(() => { const g = window.__game; g.cam.zoomAt(4, g.cam.w / 2, g.cam.h / 2); const st = g.state.stations[0]; g.cam.x = st.x; g.cam.z = st.z + 10; g.ui.selection = { kind: 'station', id: st.id }; g.refresh(); });
await page.waitForTimeout(1500);
await shot('02-zoom-station');
await act('[data-act="open-station"][data-tab="overview"]');
await shot('03-station-overview');
await act('[data-act="station-tab"][data-tab="storage"]');
await shot('04-station-storage');
await act('[data-act="station-tab"][data-tab="ships"]');
await shot('05-station-ships');
await act('[data-act="open-ship"]');
await shot('06-ship');
await act('[data-act="nav"][data-tab="fleet"]');
await shot('07-fleet');
const trader = await page.evaluate(() => window.__game.state.ships.find((s) => s.cls === 'boa').id);
await act(`[data-act="open-ship"][data-id="${trader}"]`);
await act('[data-act="trader-mode"][data-mode="route"]');
await shot('08-trader-route');
await act('[data-act="nav"][data-tab="missions"]');
await shot('09-missions');
await act('[data-act="nav"][data-tab="market"]');
await shot('10-market');
await act('[data-act="open-ware"][data-id="hullparts"]');
await shot('11-ware');
await act('[data-act="close-panel"]');
await act('[data-act="nav"][data-tab="more"]');
await shot('12-more');
await act('[data-act="nav"][data-tab="map"]');
await act('[data-act="galaxy"]');
await page.waitForTimeout(800);
await shot('13-galaxy');
await act('[data-act="open-sector"]');
await shot('14-sector');
await act('[data-act="nav"][data-tab="map"]');
await act('[data-act="place-start"]');
await page.mouse.click(200, 520);
await page.waitForTimeout(400);
await shot('15-place');
await act('[data-act="place-cancel"]');
await act('[data-act="alerts"]');
await shot('16-alerts');
console.log('errors', errors);
await browser.close();
